- name: Install required packages for munin
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: "{{ munin_packages }}"

- name: Copy munin configurations.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: munin.conf.j2
      dest: "{{ munin_dir }}/munin.conf"
    - src: hosts.conf.j2
      dest: "{{ munin_confdir }}/hosts.conf"
    - src: apache.conf.j2
      dest: "{{ munin_dir }}/apache.conf"

- name: Create munin www directory
  file: path="{{ munin_htmldir }}" owner="munin" group="munin" state=directory

- include: pagerduty_integration.yml
  when: munin_pagerduty_integration

- name: restart munin-node
  service: name=munin-node state=restarted